/**
 * Generated by qml-ng
 * Generator version: 0.3.0
 * Schema version: 1.0
 * Generated at: 2024-12-05T15:00:00.000Z
 *
 * Do not edit this file manually. Changes may be overwritten.
 * To update this component, regenerate it from the source QML file.
 */

import { Component, computed, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';

@Component({
  selector: 'app-login-form',
  standalone: true,
  imports: [MatButtonModule, MatFormFieldModule, MatInputModule],
  templateUrl: './login-form.component.html',
  styleUrl: './login-form.component.scss'
})
export class LoginFormComponent {
  readonly user = signal<any>(null);
  readonly textExpr1 = computed(() => this.user().name);
}
